anchors:
  - &latest-xcode "12.5.1"
  - &latest-ios   "14.5"
  - &min-ios      "13.7"
  - &beta-xcode   "13.0.0"
  - &beta-ios     "15.0"

executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-ReactNative
    macos:
      xcode: *latest-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashr
      FASTLANE_SKIP_UPDATE_CHECK: "true"
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-ReactNative
    macos:
      xcode: *beta-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashr
      FASTLANE_SKIP_UPDATE_CHECK: "true"

version: 2.1
jobs:
  test-ios:
    parameters:
      device:
        type: string
        default: "iPhone 12"
      ios:
        type: string
        default: *latest-ios
      nightly-test:
        type: boolean
        default: false
      env: 
        type: executor
        default: "mac"
    executor: << parameters.env >> 
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      NIGHTLY_TEST: << parameters.nightly-test >>
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            brew install gnu-sed
            npm install -g typescript
            cd iosTests
            ./prepareios.js 
      - run:
          name: Creating test_credentials.json
          command: |
            cd iosTests
            ./create_test_credentials_from_env.js
      - run:
          name: Compile
          command:  |
            cd .circleci
            fastlane build
      - run:
          name: Run Tests
          command:  |
            cd iosTests/ios
            fastlane scan --workspace SalesforceReactTestApp.xcworkspace --scheme SalesforceReactTestApp --destination "platform=iOS Simulator,name=$DEVICE,OS=$IOS_VERSION"
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/iosTests/ios/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/iosTests/ios/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/iosTests/ios/clangReport/
          destination: Static-Analysis

workflows:
  version: 2

  pr-run-tests:
    jobs:
      - test-ios

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~11:30pm Sunday/Wednesday Nights
  run-tests:
    triggers:
      - schedule:
          cron: "30 7 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - test-ios:
          name: test ReactNative iOS << matrix.ios >>
          matrix:
            parameters:
              nightly-test: [true]
              ios: [*min-ios, *latest-ios]
              device: ["iPhone 8"]
      - test-ios:
          name: test ReactNative beta iOS << matrix.ios >>
          matrix:
            parameters:
              nightly-test: [true]
              ios: [*beta-ios]
              env: [mac-beta]