#  Xcode version announcments can be found here: https://discuss.circleci.com/c/announcements/
#  Each post contains a full image manifest, including iOS runtimes, devices, CocoaPods version, etc.
#  NOTE: When updaing Xcode check the manifest for compatible chruby versions.
anchors:
  - &latest-xcode "13.4.1"
  - &beta-xcode   "14.0.0"
  - &latest-ios   "15.5"
  - &min-ios      "14.5"
  - &beta-ios     "16.0"
  - &chruby       "3.1.2"

executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-ReactNative
    macos:
      xcode: *latest-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: *chruby
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-iOS
    macos:
      xcode: *beta-xcode
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: *chruby

version: 2.1
jobs:
  test-ios:
    parameters:
      ios:
        type: string
        default: *latest-ios
      device:
        type: string
        default: "iPhone 12"
      env: 
        type: executor
        default: "mac"
    executor: << parameters.env >> 
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            brew install gnu-sed
            npm install -g typescript
            cd iosTests
            ./prepareios.js 
      - run:
          name: Creating test_credentials.json
          command: |
            cd iosTests
            ./create_test_credentials_from_env.js
      - run:
          name: Compile
          command:  |
            cd .circleci
            fastlane build
      - run:
          name: Run Tests
          command:  |
            cd iosTests/ios
            fastlane scan --workspace SalesforceReactTestApp.xcworkspace --scheme SalesforceReactTestApp --destination "platform=iOS Simulator,name=$DEVICE,OS=$IOS_VERSION"
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/iosTests/ios/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/iosTests/ios/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/iosTests/ios/clangReport/
          destination: Static-Analysis

#  Potential parameters that can come from the project GUI Triggers
parameters:
  beta:
    type: boolean
    default: false

workflows:
  version: 2

  pr-run-tests:
    when: 
      equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - test-ios

  # Build everything at 10 PM PST Sunday
  run-tests:
    when:
      not:  
        equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - test-ios:
          name: test ReactNative iOS << matrix.ios >>
          matrix:
            parameters:
              ios: [*min-ios, *latest-ios]

  # Build everything at 11 PM PST Sunday
  run-tests-beta:
    when:
      and:
        - << pipeline.parameters.beta >>
        - not:  
            equal: [ "webhook", << pipeline.trigger_source >> ]
    jobs:
      - test-ios:
          name: test ReactNative iOS << matrix.ios >>
          matrix:
            parameters:
              ios: [*beta-ios]
              device: ["iPhone 13"]
              env: ["mac-beta"]