defaults: &defaults
  working_directory: ~/SalesforceMobileSDK-ReactNative/ios/SalesforceReactTests
  macos:
    xcode: "9.4.1"
  shell: /bin/bash --login -eo pipefail
  environment:
    BASH_ENV: ~/.bashrc
    FASTLANE_SKIP_UPDATE_CHECK: true
    CHRUBY_VER: 2.5.1

version: 2
jobs:
  test-ios:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}

      - run:
          name: Installing gem dependencies
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            bundle check || sudo bundle install
            sudo bundle update

      - save_cache:
          key: v5-gems-{{ checksum ".circleci/Gemfile.lock" }}
          paths:
            - /Users/distiller/.gem/ruby/2.5.1
            - /Users/distiller/.rubies/ruby-2.4.2/lib/ruby/gems/2.5.1

      - run: 
          name: Downgrade to CocoaPods 1.4
          command:  |
            echo Y | sudo gem uninstall cocoapods
            sudo gem install cocoapods -v 1.4

      - run:
          name: Installing npm dependencies
          command: npm install

      - restore_cache:
          key: cocoapods

      - run:
          name: Installing pod dependencies
          command: pod install

      - save_cache:
          key: cocoapods
          paths:
            - /Users/distiller/Library/Caches/Cocoapods/Pods

      - run:
          name: Creating test_credentials.json
          command: touch test_credentials.json

      - run:
          name: Creating index.ios.bundle
          command: node ./updatebundle.js
      
      - run:
          name: Run Tests
          command:  |
            chruby ${CHRUBY_VER}
            cd .circleci
            fastlane "PR"

      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/ios/SalesforceReactTests/test_output/

      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/ios/SalesforceReactTests/test_output/
          destination: Test-Results

      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/ios/SalesforceReactTests/clangReport
          destination: Static-Analysis

      - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode

workflows:
  version: 2

  pr-build-all-apps:
    jobs:
      - test-ios

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~11:30pm Tuesday/Thursday Nights
  weekly-build-all-apps:
    triggers:
      - schedule:
          cron: "30 7 * * 3,5"
          filters:
            branches:
              only:
                - dev

    jobs:
      - test-ios
