executors:
  mac:
    working_directory: ~/SalesforceMobileSDK-ReactNative
    macos:
      xcode: 11.6.0
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashr
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: 2.7.1
  mac-beta:
    working_directory: ~/SalesforceMobileSDK-ReactNative
    macos:
      xcode: 12.0.0
    shell: /bin/bash --login -eo pipefail
    environment:
      BASH_ENV: ~/.bashrc
      FASTLANE_SKIP_UPDATE_CHECK: "true"
      CHRUBY_VER: 2.7.1

version: 2.1
jobs:
  test-ios:
    parameters:
      device:
        type: string
        default: "iPhone 11"
      ios:
        type: string
        default: "13.6"
      nightly-test:
        type: boolean
        default: false
      env: 
        type: executor
        default: "mac"
    executor: << parameters.env >> 
    environment:
      DEVICE: << parameters.device >>
      IOS_VERSION: << parameters.ios >>
      NIGHTLY_TEST: << parameters.nightly-test >>
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            brew install gnu-sed
            cd ios/SalesforceReactTests
            ./prepareios.js 
      - run:
          name: Creating test_credentials.json
          command: |
            cd ios/SalesforceReactTests
            node ./create_test_credentials_from_env.js
      - run:
          name: Compile
          command:  |
            cd .circleci
            fastlane build
      - run:
          name: Run Tests
          command:  |
            cd .circleci
            chruby ${CHRUBY_VER}
            sudo gem install bundler
            sudo bundle install
            sudo bundle exec fastlane test
      - store_test_results:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/.circleci/test_output
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/.circleci/test_output
          destination: Test-Results
      - store_artifacts:
          path: /Users/distiller/SalesforceMobileSDK-ReactNative/ios/SalesforceReactTests/clangReport/
          destination: Static-Analysis
      - run:
          name: Upload code coverage
          command: bash <(curl -s https://codecov.io/bash) -X gcov -X xcode

workflows:
  version: 2

  pr-run-tests:
    jobs:
      - test-ios

  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~11:30pm Sunday/Wednesday Nights
  weekly-run-tests:
    triggers:
      - schedule:
          cron: "30 7 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - test-ios:
          matrix:
            parameters:
              nightly-test: [true]
              ios: ["12.2", "13.6"]
              device: ["iPhone 8"]

  # TODO: Move this run into above matrix when Xcode 12 launches.  
  # Cron are on a timezone 8 hours ahead of PST
  # Build everything at ~12:00pm Sunday/Wednesday Nights
  weekly-run-tests-ios14:
    triggers:
      - schedule:
          cron: "00 8 * * 1,4"
          filters:
            branches:
              only:
                - dev
    jobs:
      - test-ios:
          name: "ReactNative iOS 14 Nightly"
          nightly-test: true
          env: mac-beta
          ios: "14.0"